#!/bin/sh

setwall "$HOME/pictures/wallpaper/bg.jpg" &
[[ -f "$HOME/.config/x11/xresources" ]] && xrdb -merge -I$HOME "$HOME/.config/x11/xresources"
[[ -f "$HOME/.config/x11/xmodmap" ]] && xmodmap "$HOME/.config/x11/xmodmap"
dwm_bar &
xcompmgr &
dunst &
xset r rate 200 25 &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
unclutter &

exec dwm > /dev/null 2>&1
